In [1]:
import numpy as np

In [2]:
# 查看docstring
np?

In [3]:
# 查看源码
np.sort??

In [4]:
# 直接运行py程序
%run demo_np02.py

[[ 0  1  2]
 [-3  4  0]
 [-1  3 -2]] (3, 3) [[-4 -1  2]
 [-1 -4  0]
 [ 1  5 -2]] (3, 3)
[[-1.  0.  1.]
 [-1.  0.  0.]
 [ 0.  2. -1.]] [[-3. -1.  1.]
 [ 0. -4.  0.]
 [ 1.  3. -1.]]


In [9]:
%who_ls

['A', 'B', 'X', 'Y', 'np']

In [11]:
__

['A', 'B', 'X', 'Y', 'np']

In [13]:
%logstart

Activating auto-logging. Current session state plus future input saved.
Filename       : ipython_log.py
Mode           : rotate
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active


In [14]:
x = "foobar"
y = "foo"

In [16]:
%timeit x.startswith(y)

219 ns ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [24]:
import requests

In [25]:
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"}

In [26]:
headers

{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36'}

In [27]:
all_url = "http://www.mzitu.com/all"
start_html = requests.get(all_url, headers=headers)
start_html

<Response [200]>

In [28]:
start_html.text
tree = etree.HTML(start_html.text)

'<!DOCTYPE html>\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n<title>每日更新 - 妹子图</title>\n<meta name="keywords" content="妹子图,妹子,美女图片,美女写真,性感美女" />\n<meta name="description" content="妹子图官网(www.mzitu.com)每日更新最新最全的妹子图片和高清性感美女图片,包括性感妹子,日本妹子,台湾妹子,清纯妹子以及妹子自拍分享。" />\n<meta name="mobile-agent" content="format=html5;url=http://m.mzitu.com/all/" />\n<link rel="alternate" media="only screen and(max-width: 640px)" href="http://m.mzitu.com/all/" >\n<link rel="canonical" href="http://www.mzitu.com/all/" />\n<meta http-equiv="Cache-Control" content="no-transform" />\n<meta http-equiv="Cache-Control" content="no-siteapp" />\n<meta name="applicable-device" content="pc">\n<meta name="renderer" content="webkit">\n<link href="http://file.meizitu.net/pfiles/mztcss.css" rel="stylesheet" type="text/css" />\n<link rel="shortcut icon" href="http://file.meizitu.net/pfiles/img/favicon.ico" type="image/x-icon"/>\n<link rel="apple-touch-icon-precomposed" href="http://file.