In [1]:
import numpy as np

In [2]:
np.empty((2,3,1)) #垃圾值，为初始化的值

array([[[ -1.49166815e-154],
        [  1.49457679e-154],
        [  2.23567876e-314]],

       [[  2.23582868e-314],
        [  2.23576025e-314],
        [  2.23582953e-314]]])

In [4]:
n = np.arange(15)
n.dtype

dtype('int64')

In [6]:
# int -> float64
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.dtype

dtype('int64')

In [10]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [15]:
# float->int
arr = np.array([3.7, -1.2, -2.6, 0.5, 2.9, 10.1])
arr, arr.dtype, id(arr)

(array([  3.7,  -1.2,  -2.6,   0.5,   2.9,  10.1]),
 dtype('float64'),
 4526106864)

In [17]:
# float->int 直接截断
# id(arr.astype(np.int32))
arr.astype(np.int32)

array([ 3, -1, -2,  0,  2, 10], dtype=int32)

In [14]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 2684354560, 2785180651, 3221227516,          2,
                0,  222167112,     131073], dtype=uint32)