##### numpy && pandas 

1. [numpy 100 训练](https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises.md)
2. [官方文档](https://docs.scipy.org/doc/numpy/user/whatisnumpy.html)
3. [quickstart](https://docs.scipy.org/doc/numpy/user/quickstart.html)

In [42]:
import numpy as np

In [2]:
np.__version__

'1.13.3'

In [3]:
np.show_config()

lapack_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
blis_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE


##### [创建数组对象](https://docs.scipy.org/doc/numpy/user/basics.creation.html)
###### 2.1 array()

In [9]:
# 同一种类型
x = np.array([1, 2, 3, 0])
print(x)

# 混合类型会被提升类型
y = np.array([[1, 2], [0, 0.5], (1+1j, 3.)])
print(y)

[1 2 3 0]
[[ 1.0+0.j  2.0+0.j]
 [ 0.0+0.j  0.5+0.j]
 [ 1.0+1.j  3.0+0.j]]


###### 2.2  zeros()
zeros(shape) will create an array filled with 0 values with the specified shape. The default dtype is float64.

In [11]:
# 2x3
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

###### 2.3  arange()
arange() will create arrays with regularly incrementing values

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10, dtype=np.float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [15]:
np.arange(2, 3, 0.1, dtype=np.float)

array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9])

###### 2.4  linspace()
linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.将创建具有指定数量元素的数组，并在指定的开始和结束值之间平均间隔

In [18]:
# 这个创建函数的优点是可以保证元素的数量和开始和结束点，
# 对于任意的开始，停止和步骤值，arange（）通常不会这样做
np.linspace(0., 10., 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

###### 2.5  indices() 
将创建一组数组（堆叠为一个更高维数组），每个维度一个，每个维度表示该维度中的变化

In [19]:
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

eg:[莫烦](https://morvanzhou.github.io/tutorials/data-manipulation/np-pd/2-1-np-attributes/)

In [23]:
# 列表转化为矩阵
x = np.array([[1,2,3],[2,3,4]])
print(x)
# 维数
print('number of dim:', x.ndim)
# 形状
print('shape :', x.shape)
# 元素个数
print('size  :', x.size)

[[1 2 3]
 [2 3 4]]
('number of dim:', 2)
('shape :', (2, 3))
('size  :', 6)


1. array：创建数组
2. dtype：指定数据类型
3. zeros：创建数据全为0
4. ones：创建数据全为1
5. empty：创建数据接近0
6. arrange：按指定范围创建数据
7. linspace：创建线段
8. reshape: 改变形状

In [36]:
# 3x4 全为1的矩阵
x = np.ones((3, 4), dtype=np.int)
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [46]:
# 创建全空数组, 其实每个值都是接近于零的数
y = np.empty((3, 4))
print(y)
print(y.reshape(4,3))

[[  3.10503618e+231   3.10503618e+231   2.15019798e-314   6.94970029e-310]
 [  6.94970029e-310   3.10503618e+231   2.16208110e-314   2.16208446e-314]
 [  3.10503618e+231   3.10503618e+231   3.32457344e-309   8.34402697e-309]]
[[  3.10503618e+231   3.10503618e+231   2.15019798e-314]
 [  6.94970029e-310   6.94970029e-310   3.10503618e+231]
 [  2.16208110e-314   2.16208446e-314   3.10503618e+231]
 [  3.10503618e+231   3.32457344e-309   8.34402697e-309]]


In [45]:
# 用 arange 创建连续数组, 使用 reshape 改变数据的形状
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
