#### 1 基本的矩阵运算

In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print(a, b)

(array([10, 20, 30, 40]), array([0, 1, 2, 3]))


In [4]:
c = a - b
print(c)

[10 19 28 37]


In [10]:
c = a + b
print(c)
# Numpy中的矩阵乘法分为两种， 
# 其一是前文中的对应元素相乘，
# 其二是标准的矩阵乘法运算，即对应行乘对应列得到相应元素：
c = a * b 
print(c)

[10 21 32 43]
[  0  20  60 120]


#### 2 当矩阵A的列数等于矩阵B的行数时，A与B可以相乘
1. 矩阵C的行数等于矩阵A的行数，C的列数等于B的列数。
2. 乘积C的第m行第n列的元素等于矩阵A的第m行的元素与矩阵B的第n列对应元素乘积之和

In [9]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
print(A, B)
C = A * B
# 3x3
print(C)

(array([[0],
       [1],
       [2]]), array([[0, 1, 2]]))
[[0 0 0]
 [0 1 2]
 [0 2 4]]


#### [矩阵乘法](http://dec3.jlu.edu.cn/webcourse/t000022/teach/chapter2/2_1.htm)

##### eg01
![eg01](https://raw.githubusercontent.com/hyhlinux/math/sklearn/static/images/eg01.jpg)

In [2]:
# https://morvanzhou.github.io/tutorials/data-manipulation/np-pd/2-3-np-math1/
B = np.array([[0, 1, 2], [-3, 4, 0], [-1, 3, -2]])
C = np.array([[-4, -1, 2], [-1, -4, 0], [1, 5, -2]])
print(B, B.shape, C, C.shape)

X = (C+B)/4
# X = A.__add__(B).__div__(4)
Y = B - X
print('X:', X)
print('Y:', Y)

[[ 0  1  2]
 [-3  4  0]
 [-1  3 -2]] (3, 3) [[-4 -1  2]
 [-1 -4  0]
 [ 1  5 -2]] (3, 3)
X: [[-1.  0.  1.]
 [-1.  0.  0.]
 [ 0.  2. -1.]]
Y: [[ 1.  1.  1.]
 [-2.  4.  0.]
 [-1.  1. -1.]]


##### 最大最小元素

In [4]:
print(C.mean(), C.min(), C.max())

-0.444444444444 -4 5


In [11]:
#排序 
# https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.arange.html#numpy.arange
A = np.arange(12, 0, -1).reshape((3, 4))
print(A)
print(np.sort(A))

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


#### 矩阵的转置

In [12]:
print(np.transpose(A)) # 4x3  第一列变第一行

[[12  8  4]
 [11  7  3]
 [10  6  2]
 [ 9  5  1]]


In [13]:
print(A.T)

[[12  8  4]
 [11  7  3]
 [10  6  2]
 [ 9  5  1]]


##### clip
给定一个区间，区间外的值被剪切到区间边缘。例如，如果指定[0，1]的区间，则小于0的值变为0，大于1的值变为1

In [17]:
A = np.arange(10)
print(A)
print(np.clip(A, 2, 6))

[0 1 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 6 6 6]


#### numpy 索引

##### 一维索引

In [19]:
A = np.arange(0, 12)
print(A, A[11])

[ 0  1  2  3  4  5  6  7  8  9 10 11] 11


##### 二维索引

In [24]:
A = A.reshape(3, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
# 第3行
A[2]

array([ 8,  9, 10, 11])

In [28]:
A[2][1], A[2][:3]

(9, array([ 8,  9, 10]))

In [31]:
# 行遍历
for row in A:
    print(row)

# 列遍历
print('先求转置，在行遍历')
for row in A.T:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
先求转置，在行遍历
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


##### 迭代输出
返回一个一维的数组副本

In [33]:
print(A.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


###### vstack hstack
垂直合并 水平合并

In [39]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
C = np.vstack((A, B))
print(C)
print(A.shape, C.shape)
C = np.hstack((A, B))
print(C, C.shape)

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)
[1 1 1 2 2 2] (6,)


#### 转置正对的是矩阵
选择元组中的每个新轴对象用于将所得选择的维度扩展一个单位长度维度。添加的维度是选择元组中newaxis对象的位置

In [45]:
print(A[np.newaxis,:].shape)  #1x3
print(A[:,np.newaxis])        #3x1
print(A[:,np.newaxis].shape)  #
# (3,1)

(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [44]:
#
print(A[np.newaxis,:].T, A.T)

[[1]
 [1]
 [1]] [1 1 1]


In [52]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
print(A.shape, B.shape)
print(A, B)

(3, 1) (3, 1)
[[1]
 [1]
 [1]] [[2]
 [2]
 [2]]


In [51]:
C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack
print(C, '\n\n', D)
print(C.shape,D.shape)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]] 

 [[1 2]
 [1 2]
 [1 2]]
(6, 1) (3, 2)


In [53]:
C = np.concatenate((A,B,B,A),axis=0)  #v
print(C)
D = np.concatenate((A,B,B,A),axis=1)  #h
print(D)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


#### 数组分割

In [56]:
A = np.arange(12).reshape((3, 4))
print(A.shape, '\n', A)

(3, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
# 按照列切割， 切割成两个
print(np.split(A, 2, axis=1))
print(np.hsplit(A, 2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [66]:
# 按照行切割， 切割成3个
print(np.split(A, 3, axis=0))
print(np.vsplit(A, 3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [63]:
# 不等量的分割
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
