#### 1 基本的矩阵运算

In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print(a, b)

(array([10, 20, 30, 40]), array([0, 1, 2, 3]))


In [4]:
c = a - b
print(c)

[10 19 28 37]


In [10]:
c = a + b
print(c)
# Numpy中的矩阵乘法分为两种， 
# 其一是前文中的对应元素相乘，
# 其二是标准的矩阵乘法运算，即对应行乘对应列得到相应元素：
c = a * b 
print(c)

[10 21 32 43]
[  0  20  60 120]


#### 2 当矩阵A的列数等于矩阵B的行数时，A与B可以相乘
1. 矩阵C的行数等于矩阵A的行数，C的列数等于B的列数。
2. 乘积C的第m行第n列的元素等于矩阵A的第m行的元素与矩阵B的第n列对应元素乘积之和

In [9]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
print(A, B)
C = A * B
# 3x3
print(C)

(array([[0],
       [1],
       [2]]), array([[0, 1, 2]]))
[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [5]:
# https://morvanzhou.github.io/tutorials/data-manipulation/np-pd/2-3-np-math1/
A = np.array([[1, 1], [0, 1]])
B = np.arange(4).reshape((2, 2))
print(A, B)
C = A * B
print(C)

(array([[1, 1],
       [0, 1]]), array([[0, 1],
       [2, 3]]))
[[0 1]
 [0 3]]
