In [1]:
import numpy as np


In [2]:
print(np.__version__)
np.show_config()

1.13.3
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
lapack_opt_info:
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
atlas_3_10_threads_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE


In [8]:
z = np.zeros(shape=(1, 10),dtype=float, order='C')
print(z, z.shape, z.itemsize, z.size)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]] (1, 10) 8 10


In [9]:
print("memory size:{} bytes".format(z.size*z.itemsize))

memory size:80 bytes


In [11]:
# 查看文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [15]:
z = np.zeros(shape=(10)) # 一维数组
print(z)
z[4] = 1
print(z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [18]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
z = np.arange(0, 9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
# 返回非空元素的索引下标
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 单位矩阵

In [30]:
z = np.eye(2, dtype=int)
print(z)

[[1 0]
 [0 1]]


In [29]:
z = np.eye(3, dtype=int)
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [32]:
z = np.eye(3, k=1, dtype=int)
print(z)

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [33]:
z = np.eye(3, k=-1, dtype=int)
print(z)

[[0 0 0]
 [1 0 0]
 [0 1 0]]


In [36]:
z = np.random.random(size=(3,3,3))
print(z)

[[[ 0.70505668  0.97345303  0.61713746]
  [ 0.56649594  0.40604801  0.98981818]
  [ 0.20427222  0.90428604  0.96402953]]

 [[ 0.71352013  0.54281513  0.74846888]
  [ 0.0463855   0.28358138  0.20114789]
  [ 0.55430604  0.05399703  0.27667136]]

 [[ 0.23073081  0.76937748  0.62632077]
  [ 0.10453937  0.35728152  0.6682631 ]
  [ 0.33406594  0.90055945  0.80059006]]]


In [38]:
z = np.random.random(size=(10, 10))
print(z)
print(z.min(), z.max())

[[ 0.45528889  0.60917393  0.89436796  0.28559805  0.05245733  0.69397047
   0.21763023  0.23528208  0.18008237  0.48263639]
 [ 0.17938517  0.46006172  0.0631925   0.83601832  0.95491683  0.21658189
   0.38350391  0.56263447  0.26785586  0.894781  ]
 [ 0.42793677  0.1362219   0.01594953  0.28455315  0.43981278  0.40505387
   0.62623691  0.85760541  0.61420667  0.50157011]
 [ 0.29690707  0.91225595  0.09865544  0.3183459   0.43822134  0.07553313
   0.92550503  0.42228257  0.44546448  0.3814884 ]
 [ 0.62202268  0.92456816  0.73191432  0.51647658  0.52310255  0.693619
   0.07972917  0.49649109  0.22438064  0.56287346]
 [ 0.69371785  0.74114196  0.54349881  0.29457936  0.3289035   0.84115238
   0.27963691  0.96483535  0.66403151  0.18170512]
 [ 0.57604476  0.32091447  0.38836009  0.54217025  0.96216836  0.12312288
   0.91909573  0.95104995  0.04614289  0.32625671]
 [ 0.50321484  0.46527331  0.41477498  0.05444712  0.85649196  0.95277649
   0.69476876  0.93764059  0.1591456   0.38681371]
 [

In [58]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

In [40]:
z = np.random.random(30)
print(z.mean())

0.491989925419


In [43]:
z = np.ones(shape=(10,10))
# 从第二行开始至倒数第二行， 从第一列至倒数第二列
z[1:-1,1:-1] = 0
print(z)

z = 

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [48]:
z = np.ones(shape=(5,5))
print(z)
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [56]:
# print(np.info(np.nan))
# print(np.nan, np.inf)
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
False


In [63]:
# 对角矩阵
z = np.diag(np.arange(1,5), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
