###### 交叉验证

In [1]:
%matplotlib inline

##### 导入常用模块

In [3]:
from sklearn import  preprocessing
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.datasets.samples_generator import make_classification 
from sklearn.neighbors import KNeighborsClassifier #k最邻近
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt 

In [10]:
# 加载数据
iris = load_iris()
X = iris.data
y = iris.target
list(zip(X, y))

[(array([ 5.1,  3.5,  1.4,  0.2]), 0),
 (array([ 4.9,  3. ,  1.4,  0.2]), 0),
 (array([ 4.7,  3.2,  1.3,  0.2]), 0),
 (array([ 4.6,  3.1,  1.5,  0.2]), 0),
 (array([ 5. ,  3.6,  1.4,  0.2]), 0),
 (array([ 5.4,  3.9,  1.7,  0.4]), 0),
 (array([ 4.6,  3.4,  1.4,  0.3]), 0),
 (array([ 5. ,  3.4,  1.5,  0.2]), 0),
 (array([ 4.4,  2.9,  1.4,  0.2]), 0),
 (array([ 4.9,  3.1,  1.5,  0.1]), 0),
 (array([ 5.4,  3.7,  1.5,  0.2]), 0),
 (array([ 4.8,  3.4,  1.6,  0.2]), 0),
 (array([ 4.8,  3. ,  1.4,  0.1]), 0),
 (array([ 4.3,  3. ,  1.1,  0.1]), 0),
 (array([ 5.8,  4. ,  1.2,  0.2]), 0),
 (array([ 5.7,  4.4,  1.5,  0.4]), 0),
 (array([ 5.4,  3.9,  1.3,  0.4]), 0),
 (array([ 5.1,  3.5,  1.4,  0.3]), 0),
 (array([ 5.7,  3.8,  1.7,  0.3]), 0),
 (array([ 5.1,  3.8,  1.5,  0.3]), 0),
 (array([ 5.4,  3.4,  1.7,  0.2]), 0),
 (array([ 5.1,  3.7,  1.5,  0.4]), 0),
 (array([ 4.6,  3.6,  1. ,  0.2]), 0),
 (array([ 5.1,  3.3,  1.7,  0.5]), 0),
 (array([ 4.8,  3.4,  1.9,  0.2]), 0),
 (array([ 5. ,  3. ,  1.6

In [11]:
#分割数据
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)