In [1]:
import numpy as np

In [2]:
# 查看docstring
np?

In [3]:
# 查看源码
np.sort??

In [4]:
# 直接运行py程序
%run demo_np02.py

[[ 0  1  2]
 [-3  4  0]
 [-1  3 -2]] (3, 3) [[-4 -1  2]
 [-1 -4  0]
 [ 1  5 -2]] (3, 3)
[[-1.  0.  1.]
 [-1.  0.  0.]
 [ 0.  2. -1.]] [[-3. -1.  1.]
 [ 0. -4.  0.]
 [ 1.  3. -1.]]


In [9]:
%who_ls

['A', 'B', 'X', 'Y', 'np']

In [11]:
__

['A', 'B', 'X', 'Y', 'np']

In [13]:
%logstart

Activating auto-logging. Current session state plus future input saved.
Filename       : ipython_log.py
Mode           : rotate
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active


In [14]:
x = "foobar"
y = "foo"

In [16]:
%timeit x.startswith(y)

219 ns ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [24]:
import requests

In [25]:
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"}

In [26]:
headers

{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36'}

In [27]:
all_url = "http://www.mzitu.com/all"
start_html = requests.get(all_url, headers=headers)
start_html

<Response [200]>

In [51]:
start_html.text[:10]

'<!DOCTYPE '

In [29]:
from lxml import etree

In [54]:
tree = etree.HTML(start_html.text)
# (a.text, a.attrib.get('href')) , 提交代码是只打印标签，测试时看数据。
a_list = [(a.text, a.attrib.get('href')) for a in tree.xpath("//div[contains(@class, 'all')]//li//a") if not a]

/Users/apple/.virtualenvs/math3.5/lib/python3.5/site-packages/ipykernel_launcher.py:3: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [73]:
for a in a_list[:2]:
    print(a[1])
    body = get_child_page(a[1])
    print(len(body))
    child_link_list = get_child_link(body)
    for link in child_link_list:
        print("{}/{}".format(a[1], link))

http://www.mzitu.com/114525
10770
http://www.mzitu.com/114525/1
http://www.mzitu.com/114525/2
http://www.mzitu.com/114525/3
http://www.mzitu.com/114525/4
http://www.mzitu.com/114525/…
http://www.mzitu.com/114525/65
http://www.mzitu.com/114474
10838
http://www.mzitu.com/114474/1
http://www.mzitu.com/114474/2
http://www.mzitu.com/114474/3
http://www.mzitu.com/114474/4
http://www.mzitu.com/114474/…
http://www.mzitu.com/114474/50


In [66]:
# 获取用户首页
def get_child_page(url=""):
    if not url:
        return None
    src_html = requests.get(url, headers=headers)
    if not src_html:
        return None
    return src_html.text
body = get_child_page(a_list[0][1])

In [74]:
# 获取该用户的所有分页链接
def get_child_link(html=""):
    if not html:
        return None
    child_tree = etree.HTML(html)
    span_list = child_tree.xpath("//div[contains(@class, 'pagenavi')]//span//text()")
    if span_list and len(span_list) > 2:
        span_list = span_list[1:-1]
    return span_list
get_child_link(body)

['1', '2', '3', '4', '…', '50']

In [75]:
# 获取该用户某一个分页的具体图片
def parse_img_from_child_page(url=""):
    src_html = requests.get(url, headers=headers)
    child_tree = etree.HTML(src_html.text)
    img_link = child_tree.xpath("//div[contains(@class, 'main-image')]//img/@src")
    return img_link
parse_img_from_child_page(url="http://www.mzitu.com/114525/65")

['http://i.meizitu.net/2018/01/02c65.jpg']